server.port=9090
spring.application.name=api-gateway
spring.cloud.gateway.routes[0].id=greet-service
spring.cloud.gateway.routes[0].uri=http://localhost:8082
spring.cloud.gateway.routes[0].predicates[0]=Path=/greet/**
spring.cloud.gateway.routes[0].filters[0]=StripPrefix=0
