spring.application.name=EmployeeManagementSystem

# Primary datasource - employees and departments
spring.datasource.primary.jdbc-url=jdbc:h2:mem:primarydb
spring.datasource.primary.username=sa
spring.datasource.primary.password=password
spring.datasource.primary.driver-class-name=org.h2.Driver

# Secondary datasource - audit logs
spring.datasource.secondary.jdbc-url=jdbc:h2:mem:secondarydb
spring.datasource.secondary.username=sa
spring.datasource.secondary.password=password
spring.datasource.secondary.driver-class-name=org.h2.Driver

spring.jpa.primary.hibernate.ddl-auto=update
spring.jpa.primary.show-sql=true
spring.jpa.secondary.hibernate.ddl-auto=update
spring.jpa.secondary.show-sql=true

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

server.port=8080
