server.port=9092
spring.application.name=edge-service
spring.cloud.gateway.routes[0].id=edge_route
spring.cloud.gateway.routes[0].uri=http://httpbin.org
spring.cloud.gateway.routes[0].predicates[0]=Path=/example/**
spring.cloud.gateway.routes[0].filters[0]=RewritePath=/example/(?<segment>.*), /$\{segment}
