server.port=8090
spring.application.name=payment-service
resilience4j.circuitbreaker.instances.paymentServiceCircuitBreaker.register-health-indicator=true
resilience4j.circuitbreaker.instances.paymentServiceCircuitBreaker.sliding-window-size=10
resilience4j.circuitbreaker.instances.paymentServiceCircuitBreaker.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.paymentServiceCircuitBreaker.wait-duration-in-open-state=10000
