server.port=9091
spring.application.name=api-gateway-routing
spring.cloud.gateway.routes[0].id=example-service
spring.cloud.gateway.routes[0].uri=http://httpbin.org
spring.cloud.gateway.routes[0].predicates[0]=Path=/get
spring.cloud.gateway.routes[0].filters[0]=AddRequestHeader=X-Custom-Header,Value
